name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run unit tests
        run: npm run test:unit
      # Note: Integration tests require a live server (npm run dev) and are not run in CI
      # To run integration tests locally: npm run test:int
